CREATE TABLE [dbo].[KMTUserRegistration] (
    [Id]                INT             IDENTITY (1, 1) NOT NULL,
    [UserCode]          NVARCHAR (50)   NOT NULL,
    [UserNTID]          NVARCHAR (50)   NOT NULL,
    [UserName]          NVARCHAR (50)   NOT NULL,
    [UserEmail]         NVARCHAR (50)   NOT NULL,
    [ManagerCode]       NVARCHAR (50)   NOT NULL,
    [ManagerNamel]      NVARCHAR (50)   NOT NULL,
    [ManagerNTID]       NVARCHAR (50)   NOT NULL,
    [ManagerEmail]      NVARCHAR (50)   NOT NULL,
    [Roleld]            INT             NOT NULL,
    [BusinessSegmentld] INT             NOT NULL,
    [Capabilitiesld]    INT             NOT NULL,
    [LOBId]             INT             NOT NULL,
    [UserPhoto]         VARBINARY (MAX) NOT NULL,
    [AvatarExt]         VARCHAR (50)    NULL,
    [AboutMe]           VARCHAR (140)   NOT NULL,
    [Remarks]           VARCHAR (250)   NULL,
    [Status]            INT             NOT NULL,
    [ImgStatus]         INT             NULL,
    [IsActive]          BIT             NOT NULL,
    [CreatedBy]         NVARCHAR (50)   NOT NULL,
    [CreatedOn]         DATETIME        NOT NULL,
    [ModifiedBy]        NVARCHAR (50)   NULL,
    [ModifiedOn]        DATETIME        NULL,
    [IsAdmin]           BIT             NULL
);

