USE [KMT]
GO
CREATE PROCEDURE [DBO].[uspUpdateAboutMe]
@Id INT,
@AboutMe VARCHAR(140)
AS
BEGIN
BEGIN TRANSACTION;
SAVE TRANSACTION MySavePoint;
BEGIN TRY
BEGIN
UPDATE KMTUserRegistration SET AboutMe = @AboutMe WHERE id = @Id
END
END TRY
BEGIN CATCH
IF @@TRANCOUNT > 0
BEGIN
ROLLBACK TRANSACTION MySavePoint;
END
END CATCH
COMMIT TRANSACTION
END
GO