CREATE TABLE[dbo].[KMTUserRegistration]( 
[Id] [int] IDENTITY(1,1) NOT NULL, 
[UserCode] [nvarchar](50) NOT NULL, 
[UserNTID][nvarchar](50) NOT NULL, 
[UserName] [nvarchar](50) NOT NULL, 
[UserEmail] [nvarchar](50) NOT NULL, 
[ManagerCode] [nvarchar](50) NOT NULL, 
[ManagerNamel [nvarchar](50 NOT NULL, 
[ManagerNTID][nvarchar](50 NOT NULL, 
[ManagerEmail][nvarchar](50) NOT NULL, 
[Roleld] [int] NOT NULL, 
[BusinessSegmentld] [int] NOT NULL, 
[Capabilitiesld] [int] NOT NULL, 
[LOBId] [int] NOT NULL, 
[UserPhoto] [varbinary](max) NOT NULL, 
[AvatarExt] [varchar](50) NULL, 
[AboutMe] [varchar](140) NOT NULL,
[Remarks] [varcharl(250) NULL,
[Status] [int] NOT NULL, 
[ImgStatus] [int] NULL, 
[IsActive) [bit] NOT NULL, 
[CreatedBy] [nvarchar](50) NOT NULL, 
[CreatedOn] [datetime) NOT NULL, 
[ModifiedBy] [nvarchar](50) NULL, 
[ModifiedOn] [datetime] NULL, 
[IsAdmin] [bit] NULL)