CREATE TABLE [dbo].[KMTFeedback](
[Id] [int] IDENTITY(1,1) NOT NUL,
[UserCode] [nvarchar](50) NOT NULL,
[UserNTlD] [nvarchar](50) NOT NULL,
[UserName] [nvarchar](50) NOT NULL, 
[UserEmail] [nvarchar](50) NOT NULL, 
[UserLOB] [int] NOT NULL, 
[AdminCode] [nvarchar](50) NULL, 
[AdminNTID] [nvarchar](50) NULL, 
[AdminName] [nvarchar](50) NULL, 
[AdminEmail] [nvarchar](50) NULL, 
[Feedbackld] [nvarchar](50) NOT NULL, 
[UserFeedBack] [nvarchar](500) NOT NULL, 
[AdminReply] [nvarchar](500) NULL, 
[CreatedBy] [nvarchar](50) NOT NULL, 
[CreatedOn] [datetime] NOT NULL, 
[ModifiedBy] [nvarchar](50) NULL, 
[ModifiedOn] [datetime] NULL)