CREATE TABLE [dbo].[UploadDocument](
[Id] [int]  IDENTITY(1,1) NOT NULL,
[Message] [varchar](200) NOT NULL, 
[Name] [varchar](50) NULL, 
[type] [varchar](50) NULL,
[UploadBy] [int] NOT NULL,
[UploadDate] [datetime2](7) NOT NULL, 
[Status] [int] NULL, 
[FilePath] [int] NULL,  
[Remarks] [varchar](200) NULL, 
[ApproveBy] [varchar](50) NULL,
[Approvedate] [date] NULL, 
[Title] [varchar](50) NULL,
[Category] [varchar](50) NULL, 
[CreatedBy] [varchar](50) NULL, 
[Capld] [int] NULL)