CREATE  PROCEDURE PrcLoginRequest
(
 @Name VARCHAR(50),
 @EmailId  VARCHAR(50),
 @Password  VARCHAR(50)
)
AS
BEGIN 
BEGIN TRANSACTION
SAVE TRANSACTION MYSAVEPOINT
BEGIN TRY
SELECT COUNT(*) FROM HUBREGISTRATION WHERE (Name=@Name OR EmailId =@EmailId)  AND Password = @Password;
END TRY
BEGIN CATCH
IF @@TRANCOUNT >0
BEGIN ROLLBACK TRANSACTION MYSAVEPOINT;
END;
END CATCH;
COMMIT TRANSACTION;
END;